//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustOrder
    {
        public string Sales_Order { get; set; }
        public System.DateTime Date { get; set; }
        public string Bill_to { get; set; }
        public string Ship_to_Address_Line_One { get; set; }
        public string Ship_to_City { get; set; }
        public string Ship_to_State { get; set; }
        public string Ship_to_Zipcode { get; set; }
        public string Ship_to_Country { get; set; }
        public string Customer_PO { get; set; }
        public string Ship_Via { get; set; }
        public int Quantity { get; set; }
        public string Item_ID { get; set; }
        public string Description { get; set; }
        public int Seq { get; set; }
        public bool Closed { get; set; }
    }
}
