//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FGInventoryEntities : DbContext
    {
        public FGInventoryEntities()
            : base("name=FGInventoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InventoryIn> InventoryIns { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MODEL> MODELs { get; set; }
        public virtual DbSet<Shipping> Shippings { get; set; }
        public virtual DbSet<CustOrder> CustOrders { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
    }
}
