//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelZoneMap
    {
        public int Seq { get; set; }
        public string Model { get; set; }
        public string FG { get; set; }
        public int Z2MinQty { get; set; }
        public string Zone1Code { get; set; }
        public string Zone2Code { get; set; }
        public int Z2CurtQty { get; set; }
    }
}
